"""Pydantic models for the artifact labeler output.

These models represent the structured report generated by the
search agent + writer pipeline (Phase 1 & 2 of the labeling script).
"""

from typing import Optional

from pydantic import BaseModel, Field


class VisualAudit(BaseModel):
    """Visual analysis of the artifact image."""

    scene_atmosphere: str = ""
    preservation_status: str = ""


class EntityProfile(BaseModel):
    """Core identification of the artifact."""

    standard_name: str = Field(default="未定名文物", description="Standard name of the artifact")
    era: str = Field(default="未知", description="Historical period / dynasty")
    material: str = Field(default="未知", description="Material composition")
    category: str = Field(default="未知", description="Classification category")


class AppraisalAnalysis(BaseModel):
    """Detailed appraisal with morphological and artistic analysis."""

    morphological_features: str = ""
    artistic_interpretation: str = ""
    identity_diagnosis: str = ""


class HistoricalContext(BaseModel):
    """Historical significance and context."""

    ritual_function: str = ""
    epigraphic_importance: str = ""


class ArtifactReport(BaseModel):
    """Complete structured artifact appraisal report.

    This is the JSON schema that the writer LLM is instructed to produce.
    """

    snapshot_summary: str = ""
    visual_audit: VisualAudit = VisualAudit()
    entity_profile: EntityProfile = EntityProfile()
    appraisal_analysis: AppraisalAnalysis = AppraisalAnalysis()
    historical_context: HistoricalContext = HistoricalContext()
    curatorial_conclusion: str = ""


class SearchLogEntry(BaseModel):
    """A single search turn in the investigation trace."""

    turn: int
    query: str
    result_summary: str = ""


class LabelerResult(BaseModel):
    """Full output of the artifact labeling pipeline.

    Contains the structured report, search trace, usage stats,
    and the training-ready markdown caption.
    """

    report: ArtifactReport = ArtifactReport()
    training_caption: str = ""
    search_trace: list[SearchLogEntry] = []
    usage_stats: dict = Field(default_factory=lambda: {
        "model_calls": 0,
        "search_calls": 0,
        "input_tokens": 0,
        "output_tokens": 0,
    })
    model_used: str = ""
    error: Optional[str] = None
